### PR TITLE
Update SsoLoginServlet.java

### PR DESCRIPTION
**Pull request by atporter**
Return the application referrer URL if found

proposed patch from @rkadam on #35

### CODE REVIEW

**Comment by rkadam** [comment]
Guys, I've found the fix. With this fix, things are working on our stage
environment exactly as we needed. FYI, changes are more than I mentioned in
my earlier comment.

Will add changes to fork soon. Say tuned.

Happy Friday,
Raju

**Comment by rkarodia** [comment]
I'm currently refactoring a lot of the core logic into the common https://github.com/bitium/atlassian-saml library. The fix for this has been applied in https://github.com/bitium/atlassian-saml/commit/eaad1290350da88bb706bf98fb6b25992e154655. Will the relevant issues once it's merged into master.

**Comment by rkadam** [comment]
Ramone -- It's good idea to have common library for Atlassian applications. But please note that while Confluence Wiki and JIRA applications have same way of authentication; Other Atlassian applications such as BitBucket server, Fisheye / Crucible and Bamboo do not follow or have same framework.

**Comment by rkarodia** [comment]
Fixed in this [commit](https://github.com/bitium/atlassian-saml/commit/eaad1290350da88bb706bf98fb6b25992e154655) in the common [atlassian-saml](https://github.com/bitium/atlassian-saml) library

**Pull request closed without merging**
